package.json, src/extension.ts
=> Exercise descriptions

package.json, src/extension.ts
Added a dropdown menu to Config to change the submission platform to Naos or Dodona without having to change the link in the code every time
=> Add dropdown menu to Config

src/treeView/dataClasses.ts
=> Fix empty collapse icon for exercises

src/commands/showActivityDescription.ts, src/treeView/items/activityTreeItem.ts
=> Set the viewing column for content pages to the first one

src/commands/showActivityDescription.ts
=> Open descriptions in viewcolumn 2 by default

package.json, src/api/client.ts, src/extension.ts
=> Show a message when the activity tree view is empty

package.json, src/api/managers/notificationManager.ts, src/api/resources/series.ts, src/commands/checkNotifications.ts, src/commands/openSeries.ts, src/extension.ts, src/treeView/items/seriesTreeItem.ts
Fixes #59 
(showing the notification is not really feasible right now), adding a button to open a series's description & fixing a bug preventing notifications from showing
=> Notifications Bug + Descriptions

.github/workflows/javascript.yml, .github/workflows/release.yml, .vscodeignore, RELEASING.md, package.json, scripts/get-changes.js, scripts/get-version.js, scripts/prepare-next-snapshot.js
This PR adds the ability to create releases by pushing to `release/` branches.
=> Extend automatic release pipeline

CHANGELOG.md, src/api/client.ts, src/api/managers/notificationManager.ts, src/commands/checkNotifications.ts, src/commands/completeContentPage.ts, src/commands/createNewExercise.ts, src/commands/openCourse.ts, src/commands/openSeries.ts, src/commands/showActivityDescription.ts, src/commands/submitSolution.ts, src/constants/actions.ts, src/constants/messages.ts, src/constants/urls.ts, src/treeView/dataProvider.ts, src/treeView/items/courseTreeItem.ts, src/treeView/items/seriesTreeItem.ts, src/util.ts
Fixes #43 
Also rewrites a bunch of stuff in the process to make use of `async/await` in favour of `Promise.then()`
=> Fix invalid token 401 message

src/api/client.ts, src/commands/checkNotifications.ts
=> Ignore invalid token in notifications

CHANGELOG.md, src/commands/createNewExercise.ts
=> Fix loading exercise descriptions

CHANGELOG.md, src/commands/createNewExercise.ts, src/util/naming.ts
=> Generate cleansed filenames

.github/workflows/javascript.yml, src/util/comments.ts
=> Comment syntax for new languages on Dodona added

.github/workflows/test.yml, .gitignore, .vscodeignore, codecov.yml, package.json, src/commands/submitSolution.ts, src/dodonaEnvironment.ts, src/test/commands/submitSolution.test.ts, src/test/index.ts, src/test/runner.ts, src/util/comments.test.ts, src/util/comments.ts, yarn.lock
This PR adds unit and integration tests to the repository.
=> Add unit and integration testing

.github/workflows/dependencies.yml
This PR upgrades the CI tooling by automatically approving dependabot PRs
=> Automatically approve dependabot PRs

.github/workflows/dependencies.yml
Only run on `dependabot/*` PRs.
=> Update dependencies workflow

package.json, src/test/commands/submitSolution.test.ts, yarn.lock
=> Bump dependencies

src/util/comments.ts
=> Add comment mapping for sh

src/util/naming.ts
=> Replace dashes by underscores in filenames

README.md, package.json, src/constants/urls.ts
Due to some changes on the documentation website, the links didn't work anymore.
=> Update links to documentation
